### PR TITLE
Initial draft

### PR DESCRIPTION
**Pull request by leblowl**
Hey @m-mirz, I am working on an initial draft for the file service and just wanted to get a little feedback from you in terms of direction. To start, I am using the minio-go client module for simplicity since I think we only need an S3 client and not all of aws-sdk-go, however I am open to alternatives and it's easy to change.

And then for the API design, what I am thinking so far is to have an `addFile` endpoint that accepts a `fileID` (or `key`) and a file, and then returns something like this:
```json
{
  "data": {
    "key": "the fileID/key that was passed as a parameter",
    "lastModified": "date",
    "url": "presigned url"
  }
}
```
We can add more data to the responses, but the idea I'd like to highlight is having the user pass in a `fileID` instead of having the server generate one. I think this differs from how https://git.rwth-aachen.de/acs/public/villas/web-backend-go is doing things, where a file is uploaded and an ID is generated and then returned to the user.

I see some benefits to having the user supply the ID:
1. there wouldn't be a need for an extra database to find the file in S3 - we can just use the user-supplied ID as a key in storage
2. the ID would be more meaningful to the user compared to an integer or UUID and they could easily remember it

However, it does require the user to choose a unique ID for each file.

Other API endpoints like `getFile` could accept the ID and return the URL, etc.

I am open to alternatives and we can automatically generate IDs if you'd like, and it's easy to change.

### CODE REVIEW

**Comment by leblowl** [comment]
Also, if having the user provide an ID to `addFile` is not ideal, we can generate IDs (e.g. UUIDs) server-side and then use those IDs as keys in S3. In this case, we also wouldn't need an extra database, unless we want to store additional metadata that isn't available by querying S3 (e.g. `lastModified` is already provided by the S3 API and I don't think it needs to be stored anywhere else, unless it's for performance reasons). I am just thinking of ways to simplify the service and if we don't need a PGSQL db for metadata, that sounds like a good thing to me.

**Comment by m-mirz** [comment]
Hi @leblowl, 

good idea to start with the minio-go client instead of aws-sdk-go.

I like your second suggestion regarding the fileID. This way, the user does not need to find a unique file name and we can start without the postgres DB. 

I could imagine that we might require the postgres DB for metadata eventually but omitting this part for now will get us started much faster. We will be able to use this service for the example deployment already without postgres.

Great work!

**Comment by leblowl** [comment]
@m-mirz Thanks for the feedback, I implemented the API as you suggested and I think it's ready for review now. Sorry for the large PR, I can probably break it up if desired. I added some happy path integration tests to start as I wasn't sure the level of testing needed at this point. I can do further testing if desired. And then I am wondering if you would like to setup a GitHub actions workflow for running the tests on each commit?

**Comment by m-mirz** [comment]
@leblowl Thanks! I will merge this PR. You don't have to break it up.

The CI tests can be included in the next PR :-)

**Pull request merged**
